allowBuilds:
  '@parcel/watcher': true
  es5-ext: true
  esbuild: true
  protobufjs: true
  sharp: true
  workerd: true
onlyBuiltDependencies:
  - '@parcel/watcher'
  - es5-ext
  - esbuild
  - protobufjs
  - sharp
  - workerd
